/*
 * Calc.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Calc.PCL.Http.Client;

using Calc.PCL.Models;
using Calc.PCL;
using Calc.PCL.Utilities;


namespace Calc.PCL.Exceptions
{
    public class CouldNotComputeErrorException : APIException 
    {
        // These fields hold the values for the public properties.
        private string serverMessage;
        private int serverCode;

        /// <summary>
        /// Represents the server's exception message
        /// </summary>
        [JsonProperty("ServerMessage")]
        public string ServerMessage 
        { 
            get 
            {
                return this.serverMessage; 
            } 
            private set 
            {
                this.serverMessage = value;
            }
        }

        /// <summary>
        /// Represents the server's error code
        /// </summary>
        [JsonProperty("ServerCode")]
        public int ServerCode 
        { 
            get 
            {
                return this.serverCode; 
            } 
            private set 
            {
                this.serverCode = value;
            }
        }

        /// <summary>
        /// Initialization constructor
        /// </summary>
        /// <param name="reason"> The reason for throwing exception </param>
        /// <param name="context"> The HTTP context that encapsulates request and response objects </param>
        public CouldNotComputeErrorException(string reason, HttpContext context)
            : base(reason, context)
        {
        }
    }
} 