/*
 * Calc.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using Calc.PCL;
using Calc.PCL.Utilities;
using Calc.PCL.Http.Request;
using Calc.PCL.Http.Response;
using Calc.PCL.Http.Client;
using Calc.PCL.Exceptions;

namespace Calc.PCL.Controllers
{
    public partial class OAuthAuthorizationController: BaseController
    {
        #region Singleton Pattern

        //private static variables for the singleton pattern
        private static object syncObject = new object();
        private static OAuthAuthorizationController instance = null;

        /// <summary>
        /// Singleton pattern implementation
        /// </summary>
        internal static OAuthAuthorizationController Instance
        {
            get
            {
                lock (syncObject)
                {
                    if (null == instance)
                    {
                        instance = new OAuthAuthorizationController();
                    }
                }
                return instance;
            }
        }

        #endregion Singleton Pattern

        /// <summary>
        /// Create a new OAuth 2 token.
        /// </summary>
        /// <param name="authorization">Required parameter: Authorization header in Basic auth format</param>
        /// <param name="code">Required parameter: Authorization Code</param>
        /// <param name="redirectUri">Required parameter: Redirect Uri</param>
        /// <param name="fieldParameters">Additional optional form parameters are supported by this endpoint</param>
        /// <return>Returns the Models.OAuthToken response from the API call</return>
        public Models.OAuthToken CreateRequestToken(
                string authorization,
                string code,
                string redirectUri,
                Dictionary<string, object> fieldParameters = null)
        {
            Task<Models.OAuthToken> t = CreateRequestTokenAsync(authorization, code, redirectUri, fieldParameters);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// Create a new OAuth 2 token.
        /// </summary>
        /// <param name="authorization">Required parameter: Authorization header in Basic auth format</param>
        /// <param name="code">Required parameter: Authorization Code</param>
        /// <param name="redirectUri">Required parameter: Redirect Uri</param>
        /// <param name="fieldParameters">Additional optional form parameters are supported by this endpoint</param>
        /// <return>Returns the Models.OAuthToken response from the API call</return>
        public async Task<Models.OAuthToken> CreateRequestTokenAsync(
                string authorization,
                string code,
                string redirectUri,
                Dictionary<string, object> fieldParameters = null)
        {
            //the base uri for api requests
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/xcvxv");


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "accept", "application/json" },
                { "Authorization", authorization }
            };
            _headers.Add("a", Configuration.A);

            //append form/field parameters
            var _fields = new List<KeyValuePair<string, Object>>()
            {
                new KeyValuePair<string, object>( "grant_type", "authorization_code" ),
                new KeyValuePair<string, object>( "code", code ),
                new KeyValuePair<string, object>( "redirect_uri", redirectUri )
            };
            //optional form parameters
            _fields.AddRange(APIHelper.PrepareFormFieldsFromObject("",fieldParameters, arrayDeserializationFormat: ArrayDeserializationFormat));
            //remove null parameters
            _fields = _fields.Where(kvp => kvp.Value != null).ToList();

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Post(_queryUrl, _headers, _fields);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);

            //Error handling using HTTP status codes
            if (_response.StatusCode == 400)
                throw new OAuthProviderException(@"OAuth 2 provider returned an error.", _context);

            if (_response.StatusCode == 401)
                throw new OAuthProviderException(@"OAuth 2 provider says client authentication failed.", _context);

            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return APIHelper.JsonDeserialize<Models.OAuthToken>(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        /// <summary>
        /// Obtain a new access token using a refresh token
        /// </summary>
        /// <param name="authorization">Required parameter: Authorization header in Basic auth format</param>
        /// <param name="refreshToken">Required parameter: Refresh token</param>
        /// <param name="scope">Optional parameter: Requested scopes as a space-delimited list.</param>
        /// <param name="fieldParameters">Additional optional form parameters are supported by this endpoint</param>
        /// <return>Returns the Models.OAuthToken response from the API call</return>
        public Models.OAuthToken CreateRefreshToken(
                string authorization,
                string refreshToken,
                string scope = null,
                Dictionary<string, object> fieldParameters = null)
        {
            Task<Models.OAuthToken> t = CreateRefreshTokenAsync(authorization, refreshToken, scope, fieldParameters);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// Obtain a new access token using a refresh token
        /// </summary>
        /// <param name="authorization">Required parameter: Authorization header in Basic auth format</param>
        /// <param name="refreshToken">Required parameter: Refresh token</param>
        /// <param name="scope">Optional parameter: Requested scopes as a space-delimited list.</param>
        /// <param name="fieldParameters">Additional optional form parameters are supported by this endpoint</param>
        /// <return>Returns the Models.OAuthToken response from the API call</return>
        public async Task<Models.OAuthToken> CreateRefreshTokenAsync(
                string authorization,
                string refreshToken,
                string scope = null,
                Dictionary<string, object> fieldParameters = null)
        {
            //the base uri for api requests
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/xcvxv");


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "accept", "application/json" },
                { "Authorization", authorization }
            };
            _headers.Add("a", Configuration.A);

            //append form/field parameters
            var _fields = new List<KeyValuePair<string, Object>>()
            {
                new KeyValuePair<string, object>( "grant_type", "refresh_token" ),
                new KeyValuePair<string, object>( "refresh_token", refreshToken ),
                new KeyValuePair<string, object>( "scope", scope )
            };
            //optional form parameters
            _fields.AddRange(APIHelper.PrepareFormFieldsFromObject("",fieldParameters, arrayDeserializationFormat: ArrayDeserializationFormat));
            //remove null parameters
            _fields = _fields.Where(kvp => kvp.Value != null).ToList();

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Post(_queryUrl, _headers, _fields);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);

            //Error handling using HTTP status codes
            if (_response.StatusCode == 400)
                throw new OAuthProviderException(@"OAuth 2 provider returned an error.", _context);

            if (_response.StatusCode == 401)
                throw new OAuthProviderException(@"OAuth 2 provider says client authentication failed.", _context);

            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return APIHelper.JsonDeserialize<Models.OAuthToken>(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

    }
} 