/*
 * Calc.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using Calc.PCL;
using Calc.PCL.Utilities;
using Calc.PCL.Http.Request;
using Calc.PCL.Http.Response;
using Calc.PCL.Http.Client;
using Calc.PCL.Exceptions;

namespace Calc.PCL.Controllers
{
    public partial class SimpleCalculatorController: BaseController
    {
        #region Singleton Pattern

        //private static variables for the singleton pattern
        private static object syncObject = new object();
        private static SimpleCalculatorController instance = null;

        /// <summary>
        /// Singleton pattern implementation
        /// </summary>
        internal static SimpleCalculatorController Instance
        {
            get
            {
                lock (syncObject)
                {
                    if (null == instance)
                    {
                        instance = new SimpleCalculatorController();
                    }
                }
                return instance;
            }
        }

        #endregion Singleton Pattern

        /// <summary>
        /// Calculate
        /// </summary>
        /// <param name="operation">Required parameter: The operator to apply on the variables</param>
        /// <param name="x">Required parameter: The LHS value</param>
        /// <param name="y">Required parameter: The RHS value</param>
        /// <return>Returns the double response from the API call</return>
        public double GetCalculate(Models.OperationEnum operation, double x, double y)
        {
            Task<double> t = GetCalculateAsync(operation, x, y);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// Calculate
        /// </summary>
        /// <param name="operation">Required parameter: The operator to apply on the variables</param>
        /// <param name="x">Required parameter: The LHS value</param>
        /// <param name="y">Required parameter: The RHS value</param>
        /// <return>Returns the double response from the API call</return>
        public async Task<double> GetCalculateAsync(Models.OperationEnum operation, double x, double y)
        {
            //the base uri for api requests
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/{operation}");

            //process optional template parameters
            APIHelper.AppendUrlWithTemplateParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "operation", Models.OperationEnumHelper.ToValue(operation) }
            });

            //process optional query parameters
            APIHelper.AppendUrlWithQueryParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "x", x },
                { "y", y }
            },ArrayDeserializationFormat,ParameterSeparator);


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" }
            };
            _headers.Add("a", Configuration.A);

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Get(_queryUrl,_headers);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);

            //Error handling using HTTP status codes
            if (_response.StatusCode == 412)
                throw new CouldNotComputeErrorException(@"Could not compute the requested calculation", _context);

            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return double.Parse(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

    }
} 