/*
 * Calc.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Calc.PCL;
using Calc.PCL.Utilities;

namespace Calc.PCL.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum OperationEnum
    {
        SUM, //TODO: Write general description for this method
        SUBTRACT, //TODO: Write general description for this method
        MULTIPLY, //TODO: Write general description for this method
        DIVIDE, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type OperationEnum
    /// </summary>
    public static class OperationEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "SUM", "SUBTRACT", "MULTIPLY", "DIVIDE" };

        /// <summary>
        /// Converts a OperationEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The OperationEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(OperationEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case OperationEnum.SUM:
                case OperationEnum.SUBTRACT:
                case OperationEnum.MULTIPLY:
                case OperationEnum.DIVIDE:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of OperationEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of OperationEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<OperationEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into OperationEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed OperationEnum value</returns>
        public static OperationEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type OperationEnum", value));

            return (OperationEnum) index;
        }
    }
} 