/*
 * Calc.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using Calc.PCL.Controllers;
using Calc.PCL.Http.Client;
using Calc.PCL.Utilities;

namespace Calc.PCL
{
    public partial class CalcClient
    {

        /// <summary>
        /// Singleton access to SimpleCalculator controller
        /// </summary>
        public SimpleCalculatorController SimpleCalculator
        {
            get
            {
                return SimpleCalculatorController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to OAuthAuthorization controller
        /// </summary>
        public OAuthAuthorizationController OAuthAuthorization
        {
            get
            {
                return OAuthAuthorizationController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Authorization instance

        public AuthManager Auth
        {
            get { return AuthManager.Instance; }
        }

        #endregion
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public CalcClient() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public CalcClient(string a, string oAuthClientId, string oAuthClientSecret, string oAuthRedirectUri)
        {
            Configuration.A = a;
            Configuration.OAuthClientId = oAuthClientId;
            Configuration.OAuthClientSecret = oAuthClientSecret;
            Configuration.OAuthRedirectUri = oAuthRedirectUri;
        }
        #endregion
    }
}